meta-llama/llama-stack-client-python

src/llama_stack_client/_utils/_transform.py
src/llama_stack_client/resources/datasets.py
src/llama_stack_client/resources/inference.py
src/llama_stack_client/resources/memory_banks.py
src/llama_stack_client/resources/shields.py
src/llama_stack_client/types/dataset_list_response.py
src/llama_stack_client/types/dataset_register_params.py
src/llama_stack_client/types/dataset_retrieve_response.py
src/llama_stack_client/types/inference_chat_completion_params.py
src/llama_stack_client/types/inference_completion_params.py
src/llama_stack_client/types/inference_embeddings_params.py
src/llama_stack_client/types/memory_bank_register_params.py
src/llama_stack_client/types/shield.py
src/llama_stack_client/types/shield_register_params.py
tests/api_resources/test_datasets.py
tests/api_resources/test_inference.py
tests/api_resources/test_memory_banks.py
tests/api_resources/test_shields.py

- sync w/ latest OpenAPI spec: https://github.com/meta-llama/llama-stack/commit/94a6f578123fcbf56d7ea70532d38d8ce084d846

sync sdk w/ 94a6f57

---

src/llama_stack_client/lib/cli/datasets/list.py
src/llama_stack_client/lib/cli/eval_tasks/list.py
src/llama_stack_client/lib/cli/memory_banks/memory_banks.py
src/llama_stack_client/lib/cli/models/models.py
src/llama_stack_client/lib/cli/providers/list.py
src/llama_stack_client/lib/cli/scoring_functions/list.py
src/llama_stack_client/lib/cli/shields/shields.py

use rich for output formatting

---

src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/event_logger.py

The assert errors from the server are not returned to the client and hid by the 500 internal server error. Updated the server code (https://github.com/meta-llama/llama-stack/pull/493) to send the error and this client can print the error.
Please describe:
- tests you ran to verify your changes with result summaries.
- provide instructions so it can be reproduced.
1. Kick off the server with `llama stack run /Users/henrytai/.llama/distributions/llamastack-ollama/ollama-run.yaml --port 5050`
1. Trigger an error case from client. The example is `PYTHONPATH=. python -m examples.agents.client localhost 5050` from the `llama-stack-apps` repo. The issue details:  "This is a known issue with Llama3.2-3B-Instruct on ollama, where the model produces bad tool calling outputs. In this case, the …

print the error sent from the server

---

src/llama_stack_client/lib/cli/eval/run_benchmark.py
src/llama_stack_client/lib/cli/eval/run_scoring.py

[CLI] rename underscore to hyphen

---

src/llama_stack_client/types/agents/turn_create_response.py

with fixes in https://github.com/meta-llama/llama-stack/pull/587

sync stainless text_delta

---

.github/workflows/publish-to-test-pypi.yml
src/llama_stack_client/_version.py

- as title
- https://test.pypi.org/manage/project/llama-stack-client/settings/publishing/
**Checking that the uploaded package have set version correctly**

[CICD] llama-stack-client nightly package github workflow

---

src/llama_stack_client/_client.py
src/llama_stack_client/_models.py
src/llama_stack_client/types/__init__.py
src/llama_stack_client/types/agents/turn_create_response.py
src/llama_stack_client/types/inference_chat_completion_response.py
src/llama_stack_client/types/shared/__init__.py
src/llama_stack_client/types/shared/content_delta.py
src/llama_stack_client/types/shared/tool_response_message.py
src/llama_stack_client/types/shared_params/tool_response_message.py
src/llama_stack_client/types/tool.py
src/llama_stack_client/types/tool_def.py
src/llama_stack_client/types/tool_def_param.py
tests/api_resources/test_agents.py
tests/test_models.py

See https://github.com/meta-llama/llama-stack/pull/758 for the changes in types

Use ContentDelta for chat completion and agent turns

---

src/llama_stack_client/_client.py
src/llama_stack_client/_wrappers.py
src/llama_stack_client/resources/datasets.py
src/llama_stack_client/resources/eval_tasks.py
src/llama_stack_client/resources/memory_banks.py
src/llama_stack_client/resources/models.py
src/llama_stack_client/resources/post_training/job.py
src/llama_stack_client/resources/providers.py
src/llama_stack_client/resources/scoring_functions.py
src/llama_stack_client/resources/shields.py
src/llama_stack_client/resources/toolgroups.py
src/llama_stack_client/resources/tools.py
src/llama_stack_client/types/dataset_list_response.py
src/llama_stack_client/types/eval_task_list_response.py
src/llama_stack_client/types/memory_bank_list_response.py
src/llama_stack_client/types/model_list_response.py
src/llama_stack_client/types/post_training/job_list_response.py
src/llama_stack_client/types/provider_list_response.py
src/llama_stack_client/types/scoring_function_list_response.py
src/llama_stack_client/types/shield_list_response.py
src/llama_stack_client/types/tool_list_response.py
src/llama_stack_client/types/toolgroup_list_response.py
tests/test_client.py

- add `unwrap_response_fields: [data]`
```python
from llama_stack_client import LlamaStackClient
from rich.pretty import pprint
client = LlamaStackClient(base_url="http://localhost:5000")
pprint(client.models.list())
```

Unwrapping for "data"

---

src/llama_stack_client/_client.py
src/llama_stack_client/types/provider_info.py

added new API filed to providers list result

Sync updates from stainless branch: dineshyv/dev

---

src/llama_stack_client/lib/agents/event_logger.py
src/llama_stack_client/types/agents/turn.py
src/llama_stack_client/types/agents/turn_create_params.py
src/llama_stack_client/types/shared/content_delta.py
src/llama_stack_client/types/shared/interleaved_content.py
src/llama_stack_client/types/shared/interleaved_content_item.py
src/llama_stack_client/types/shared_params/interleaved_content.py
src/llama_stack_client/types/shared_params/interleaved_content_item.py
src/llama_stack_client/types/tool_runtime/document_param.py

Client SDK changes for multimodal + toolcall delta changes

Sync updates from stainless branch: ashwinb/dev

---

.gitignore
src/llama_stack_client/lib/cli/models/models.py
src/llama_stack_client/lib/cli/shields/shields.py

Better rendering to avoid truncating most important pieces of information
Small width
Large width

Improve models, shields list tables

---

src/llama_stack_client/lib/agents/agent.py

Adds non-streaming support for agent.create_turn, which returns the turn object and user can access the output_message like so:
```
response = rag_agent.create_turn(
messages=[{"role": "user", "content": prompt}],
session_id=session_id,
stream=False,
)
response.output_message
```
Modified hello.py example to use stream=False and print output_message.

non-streaming support for agent create turn

---

src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/output_parser.py
src/llama_stack_client/lib/agents/react/output_parser.py

- address comments in https://github.com/meta-llama/llama-stack-client-python/pull/121
- see https://github.com/meta-llama/llama-stack-apps/pull/166

minor fix up react_agent

---

pyproject.toml

update repo link

---

src/llama_stack_client/lib/agents/event_logger.py

Summary:
Test Plan:
Run in llama-stack-apps
python -m examples.agents.hello localhost 5001

feat: add type hints to event logger util

---

src/llama_stack_client/_utils/_sync.py
src/llama_stack_client/types/shared/agent_config.py
src/llama_stack_client/types/shared_params/agent_config.py
tests/api_resources/test_agents.py

- adapt to https://github.com/meta-llama/llama-stack/pull/1012
[Describe the tests you ran to verify your changes with result summaries. *Provide clear instructions so the plan can be easily re-executed.*]

feat: enable_persist: sync updates from stainless branch: yanxi0830/dev

---

src/llama_stack_client/_client.py
src/llama_stack_client/resources/__init__.py
src/llama_stack_client/resources/eval/eval.py
src/llama_stack_client/types/__init__.py
src/llama_stack_client/types/benchmark_config_param.py
tests/api_resources/test_eval.py

- See https://github.com/meta-llama/llama-stack/pull/1186
- Test in https://github.com/meta-llama/llama-stack/pull/1186

chore: deprecate eval task (Sync updates from stainless branch: main)

---

src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/client_tool.py
src/llama_stack_client/lib/agents/react/agent.py

passing a custom_config was failing 
```
python -m examples.agents.react_agent
```

fix: React agent should be able to work with provided config

---

src/llama_stack_client/_base_client.py
src/llama_stack_client/_client.py
src/llama_stack_client/_files.py
src/llama_stack_client/_response.py
src/llama_stack_client/_utils/_logs.py
src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/event_logger.py
src/llama_stack_client/resources/agents/turn.py
src/llama_stack_client/types/agents/__init__.py
src/llama_stack_client/types/agents/turn_create_params.py
src/llama_stack_client/types/agents/turn_response_event_payload.py
src/llama_stack_client/types/agents/turn_resume_params.py
tests/api_resources/agents/test_turn.py
tests/test_client.py

- Adapt to https://github.com/meta-llama/llama-stack/pull/1178
- test in following PR

feat (1/n): agents resume turn (Sync updates from stainless branch: yanxi0830/dev)

---

src/llama_stack_client/_client.py
src/llama_stack_client/_files.py
src/llama_stack_client/_response.py
src/llama_stack_client/resources/agents/turn.py
src/llama_stack_client/resources/inference.py
src/llama_stack_client/types/agents/turn_resume_params.py
src/llama_stack_client/types/inference_embeddings_params.py
src/llama_stack_client/types/shared/query_result.py
src/llama_stack_client/types/tool_invocation_result.py
src/llama_stack_client/types/tool_response.py
tests/api_resources/test_inference.py

- as title
```
LLAMA_STACK_CONFIG=fireworks pytest -v tests/client-sdk/agents/test_agents.py --inference-model meta-llama/Llama-3.1-8B-Instruc
```

v0.1.4 - Sync updates from stainless branch: yanxi0830/dev

---

src/llama_stack_client/lib/agents/react/agent.py

Change the apps repo to reflect this -- https://github.com/meta-llama/llama-stack-apps/pull/188/files
```
python -m examples.agents.react_agent localhost 8321
```

fix react agent

---

src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/client_tool.py
uv.lock

- See https://github.com/meta-llama/llama-stack/pull/1309/files
- See https://github.com/meta-llama/llama-stack/pull/1309/files

feat: unify max infer iters with server/client tools

---

src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/client_tool.py

Summary:
Corresponding change on the python client for https://github.com/meta-llama/llama-stack/pull/1426
Test Plan:
Tested in https://github.com/meta-llama/llama-stack/pull/1426

feat: support client tool output metadata

---

src/llama_stack_client/_utils/_logs.py

Summary:
Test Plan:
Before
After
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/meta-llama/llama-stack-client-python/pull/177).
* #178
* __->__ #177

chore: use rich to format logs

---

src/llama_stack_client/lib/agents/agent.py

Summary:
Test Plan:
test_agents.py integration tests

feat(agent): support plain function as client_tool

---

docs/cli_reference.md
scripts/gen_cli_doc.py
src/llama_stack_client/lib/cli/llama_stack_client.py

- Add script to autogen CLI reference doc
```
python scripts/gen_cli_doc.py
```

feat: autogen llama-stack-client CLI reference doc

---

src/llama_stack_client/lib/agents/agent.py

Summary:
Test Plan:
test with script in: https://github.com/meta-llama/llama-stack-apps/blob/async_agent/examples/agents/async_agent.py

chore: AsyncAgent should use ToolResponse instead of ToolResponseMessage

---

src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/agents/react/prompts.py

Summary:
1. update prompt to match the json response object
2. call tools with tool_args when present (e.g. vector_db_ids for rag tool)
Test Plan:
Run react agent with rag tool
```
react_agent_with_vector_db = ReActAgent(
client=client,
model=model_id,
tools=[
{
"name": "builtin::rag",
"args": {"vector_db_ids": [vector_db_id]},
}
],
)
react_agent_with_vector_db_config = react_agent_with_vector_db.agent_config
react_tool_parser = react_agent_with_vector_db.tool_parser
react_agent_client_tools = react_agent_with_vector_db.client_tools
results_vector_db_agent = evaluator_no_context.run(
react_agent_with_vector_db_config,
client,
num_examples=100,
client_tools=[],
tool_parser=react_tool_parser,
json_response_format=True,
)
```

fix: react agent

---

src/llama_stack_client/types/chat_completion_response_stream_chunk.py
src/llama_stack_client/types/completion_response.py
src/llama_stack_client/types/shared/chat_completion_response.py
src/llama_stack_client/types/shared/tool_response_message.py
src/llama_stack_client/types/shared_params/tool_response_message.py

[Provide a short summary of what this PR does and why. Link to relevant issues if applicable.]
[Describe the tests you ran to verify your changes with result summaries. *Provide clear instructions so the plan can be easily re-executed.*]

chore: Sync updates from stainless branch: ehhuang/dev

---

src/llama_stack_client/lib/agents/agent.py

Summary:
Supported by https://github.com/meta-llama/llama-stack/pull/1556
Test Plan:
Tested in https://github.com/meta-llama/llama-stack/pull/1556

feat(agent): support multiple tool calls

---

src/llama_stack_client/resources/providers.py
src/llama_stack_client/types/provider_get_response.py
src/llama_stack_client/types/provider_info.py
tests/api_resources/test_providers.py

- sync with https://github.com/meta-llama/llama-stack/pull/1627
```
llama-stack-client providers list
```
cc @cdoern  to fix `llama-stack-client provider get <provider_id>` CLI

chore: Sync updates from stainless branch: main

---

src/llama_stack_client/lib/agents/client_tool.py
src/llama_stack_client/lib/agents/react/tool_parser.py
src/llama_stack_client/resources/datasets.py
src/llama_stack_client/types/dataset_iterrows_params.py
src/llama_stack_client/types/dataset_iterrows_response.py
src/llama_stack_client/types/dataset_register_params.py
src/llama_stack_client/types/shared/tool_call.py
src/llama_stack_client/types/shared_params/tool_call.py

Added `ToolCall.arguments_json` to allow for json strings to be passed to client 
pytest -s -v --stack-config=fireworks tests/integration/inference/test_text_inference.py  --text-model meta-llama/Llama-3.1-8B-Instruct

Sync updates from stainless branch: hardikjshah/dev

---

src/llama_stack_client/lib/cli/eval/run_benchmark.py
src/llama_stack_client/lib/cli/eval/utils.py

add weighted_average aggreagtion function support for https://github.com/meta-llama/llama-stack/pull/1708

feat: add weighted_average aggregation function support

---

src/llama_stack_client/lib/cli/models/models.py

[Provide a short summary of what this PR does and why. Link to relevant issues if applicable.]
```
from:
$ llama-stack-client models
Usage: llama-stack-client models [OPTIONS] COMMAND [ARGS]...
Manage GenAI models.
Options:
--help  Show this message and exit.
Commands:
get         Show available llama models at distribution endpoint <<<--
list        Show available llama models at distribution endpoint
to:
$ llama-stack-client models
Usage: llama-stack-client models [OPTIONS] COMMAND [ARGS]...
Manage GenAI models.
Options:
--help  Show this message and exit.
Commands:
get         Show details of a specific model at the distribution endpoint <<<--
list        Show available llama models at distribution endpoint
```
[//]: …

fix: fix duplicate model get help text

---

src/llama_stack_client/resources/eval/jobs.py
src/llama_stack_client/resources/post_training/post_training.py
src/llama_stack_client/types/__init__.py
src/llama_stack_client/types/algorithm_config_param.py
src/llama_stack_client/types/eval/__init__.py
src/llama_stack_client/types/eval/job_status_response.py
src/llama_stack_client/types/job.py
src/llama_stack_client/types/post_training_supervised_fine_tune_params.py
src/llama_stack_client/types/tool_invocation_result.py
tests/api_resources/eval/test_jobs.py

[Provide a short summary of what this PR does and why. Link to relevant issues if applicable.]
[Describe the tests you ran to verify your changes with result summaries. *Provide clear instructions so the plan can be easily re-executed.*]

Sync updates from stainless branch: yanxi0830/dev

---

src/llama_stack_client/lib/agents/agent.py

We use extra headers to pass provider data if you wanted to override the provider data on a per-API-call basis. Normally provider data is set via LlamaStackClient initialization and is passed down in each API call automatically.

fix: accept extra_headers in agent.create_turn and pass them faithfully

---

examples/mcp_agent.py
pyproject.toml
src/llama_stack_client/lib/__init__.py
src/llama_stack_client/lib/agents/agent.py
src/llama_stack_client/lib/tools/mcp_oauth.py

Our model sucks at correct tool calling but other than things are working.

feat: add client-side utility for getting OAuth tokens simply
