meta-llama/llama-stack-client-python

- src/llama_stack_client/lib/cli/memory_banks/list.py
- src/llama_stack_client/lib/cli/models/get.py
- src/llama_stack_client/lib/cli/models/list.py
- src/llama_stack_client/lib/cli/providers.py
- src/llama_stack_client/lib/cli/shields/list.py
- fix https://github.com/meta-llama/llama-stack-client-python/issues/8
> [bugfix] llama-stack-client endpoint fix

- pyproject.toml
- requirements-dev.lock
- requirements.lock
- src/llama_stack_client/lib/cli/__init__.py
- src/llama_stack_client/lib/cli/common/utils.py
- src/llama_stack_client/lib/cli/eval/run_benchmark.py
- src/llama_stack_client/lib/cli/llama_stack_client.py
- fixes typo w/ together api key for client
- visualize eval results for categorical scores 
- Note: SimpleQA has "app" as type b/c we do not pre-register any SimpleQA specific scoring functions, and uses LLMAsJudge w/ prompt template as scoring function. 
```
llama-stack-client eval run_benchmark meta-reference-simpleqa --num-examples 5 --output-dir ./ --eval-task-config ~/eval_task_config_simpleqa.json --visualize
```
```yaml
{
"type": "app",
"eval_candidate": {
"type": "model",
"model": "Llama3.1-405B-Instruct",
"sampling_params": {
"strategy": "greedy",
"temperature": 0,
"top_p": 0.95,
"top_k": 0,
"max_tokens": 0,
"repetition_penalty": 1.0
}
},
"scoring_params": {
"llm-as-judge::llm_as_judge_base": {
"type": "llm_as_judge",
"judge_model": "Llama3.1-405B-Instruct",
"prompt_template": …
```
> [CLI] visualize categorical scores eval results with bars

- src/llama_stack_client/lib/cli/datasets/datasets.py
- src/llama_stack_client/lib/cli/datasets/register.py
- src/llama_stack_client/lib/cli/eval/eval.py
- src/llama_stack_client/lib/cli/eval/run_benchmark.py
- src/llama_stack_client/lib/cli/eval/run_scoring.py
- Update dataset register CLI to have flexibility to take input files
- Run app eval on custom dataset
-  (1) via `--dataset-path` to read rows locally
-  (2) via `--dataset-id` to read
```
llama-stack-client eval run_scoring braintrust::answer-correctness braintrust::factuality \
--dataset-path <path-to-local-dataset> \
--output-dir ./ \
--num-examples 5
```
```
llama-stack-client datasets register --dataset-id <custom-dataset-id> \
--schema '{"generated_answer": {"type": "string"}, "expected_answer": {"type": "string"}, "input_query": {"type": "string"}}' \
--dataset-path <local-file-path> \
--provider-id huggingface-0
```
```
llama-stack-client eval run_scoring \
braintrust::answer-correctness braintrust::factuality \
--dataset-id <custom-dataset-id> --output-dir ./ 
```
> [Evals] CLI for scoring custom datasets

- src/llama_stack_client/lib/direct/direct.py
- src/llama_stack_client/lib/direct/test.py
needs to go in after https://github.com/meta-llama/llama-stack/pull/477
test plan:
1) pip install -e . on llama stack main
2) pip install -e . in llama stack client python
3) run a app with direct client:
```
import asyncio
from llama_stack_client.lib.direct.direct import LlamaStackDirectClient
async def main():
client = await LlamaStackDirectClient.from_template("ollama")
response = await client.models.list()
print(response)
if __name__ == "__main__":
asyncio.run(main())
```
```
INFERENCE_MODEL=llama3.2:1b-instruct-fp16 python app.py
Resolved 12 providers
inner-inference => ollama
inner-memory => faiss
models => __routing_table__
inference => __autorouted__
inner-safety => llama-guard
shields => __routing_table__
safety => __autorouted__
memory_banks => __routing_table__
memory => …
```
> add ability to instantiate direct client with template

- pyproject.toml
- src/llama_stack_client/resources/inference.py
- src/llama_stack_client/types/inference_chat_completion_params.py
- src/llama_stack_client/types/inference_completion_params.py
- tests/api_resources/test_inference.py
- fix streaming for inference
```yaml
methods:
chat_completion: 
type: http
endpoint: post /alpha/inference/chat-completion
streaming:
skip: [ kotlin ]
param_discriminator: stream
completion: 
type: http
endpoint: post /alpha/inference/completion
streaming:
skip: [ kotlin ]
param_discriminator: stream
embeddings: post /alpha/inference/embeddings
```
```
python -m examples.inference.client localhost 5000
```
> sdk 0.0.53rc5 - fix streaming

- src/llama_stack_client/lib/cli/inference/__init__.py
- src/llama_stack_client/lib/cli/inference/inference.py
- src/llama_stack_client/lib/cli/llama_stack_client.py
- adding `llama-stack-client inference chat_completion` to quickly test a client example w/o getting apps
**Non-Streaming**
```
llama-stack-client inference chat_completion --message "hello, what model are you"
```
**Streaming**
```
llama-stack-client inference chat_completion --message "hello, what model are you" --stream
```
> [CLI] chat_completion CLI

- src/llama_stack_client/lib/cli/inference/inference.py
- src/llama_stack_client/lib/direct/direct.py
Adds https://github.com/meta-llama/llama-stack/pull/404 to DirectClient:
```
$ python src/llama_stack_client/lib/direct/test.py <run.yaml>
Please install needed dependencies using the following commands:
pip install blobfile scikit-learn transformers matplotlib lm-format-enforcer scipy tqdm accelerate nltk redis chardet torch torchvision zmq numpy sentencepiece faiss-cpu fairscale pillow pypdf psycopg2-binary pandas aiosqlite
[...]
ModuleNotFoundError: No module named 'aiosqlite'
```
> Add direct install helper print

- src/llama_stack_client/lib/cli/llama_stack_client.py
- move api keys to request headers in https://github.com/meta-llama/llama-stack/pull/535
```
llama-stack-client eval run-scoring braintrust::factuality --dataset-path <path/to/dataset> --output-dir ./ --visualize --num-examples 5
```
> add openai api_key to provider_data

- pyproject.toml
- requirements-dev.lock
- requirements.lock
Fix issue w/ just installing llama-stack-client only w/o llama-stack. 
```
$ llama-stack-client configure
Traceback (most recent call last):
File "/Users/rsm/miniforge3/bin/llama-stack-client", line 5, in <module>
from llama_stack_client.lib.cli.llama_stack_client import main
File "/Users/rsm/miniforge3/lib/python3.12/site-packages/llama_stack_client/lib/cli/llama_stack_client.py", line 19, in <module>
from .inference import inference
File "/Users/rsm/miniforge3/lib/python3.12/site-packages/llama_stack_client/lib/cli/inference/__init__.py", line 7, in <module>
from .inference import inference
File "/Users/rsm/miniforge3/lib/python3.12/site-packages/llama_stack_client/lib/cli/inference/inference.py", line 13, in <module>
from ...inference.event_logger import EventLogger
File …
```
> [bugfix] add termcolor dep

- src/llama_stack_client/lib/cli/inference/inference.py
Summary:
After we added embeddings, the default model selection in the client may pick embeddings model and return an error. See the example below:
```
llama-stack-client --endpoint http://localhost:$LLAMA_STACK_PORT models list
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ identifier                       ┃ provider_id           ┃ provider_resource_id      ┃ metadata                       ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ all-MiniLM-L6-v2                 │ sentence-transformers │ all-MiniLM-L6-v2          │ {'embedding_dimension': 384.0} │
│ meta-llama/Llama-3.2-3B-Instruct │ ollama                │ …
```
> Fix client picking embeddings model by default for chat completion

- src/llama_stack_client/_client.py
- src/llama_stack_client/lib/agents/agent.py
- src/llama_stack_client/lib/agents/client_tool.py
- src/llama_stack_client/lib/cli/inspect/__init__.py
- src/llama_stack_client/lib/cli/inspect/inspect.py
- src/llama_stack_client/lib/cli/inspect/version.py
- src/llama_stack_client/lib/cli/llama_stack_client.py
- src/llama_stack_client/lib/cli/post_training/post_training.py
- src/llama_stack_client/resources/inspect.py
- src/llama_stack_client/types/__init__.py
- src/llama_stack_client/types/version_info.py
- tests/api_resources/test_inspect.py
- tests/test_client.py
- sync SDK with /version endpoint
- llama-stack-client inspect version CLI
**Notes on version**
```
llama-stack-client --version
```
- this print outs the version of the llama-stack-client package (equivalent to pip list | grep llama-stack-client)
```
llama-stack-client inspect version
```
- this gets the server endpoint's version
> sync SDK with /version endpoint & llama-stack-client inspect version CLI

- src/llama_stack_client/lib/cli/llama_stack_client.py
- src/llama_stack_client/lib/cli/models/models.py
- src/llama_stack_client/lib/cli/toolgroups/__init__.py
- src/llama_stack_client/lib/cli/toolgroups/toolgroups.py
add llama stack client subcommand for tool groups
test plan:
```
llama-stack-client toolgroups list
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━┳━━━━━━━━━━━━━━┓
┃ identifier                ┃ provider_id            ┃ args ┃ mcp_endpoint ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━╇━━━━━━━━━━━━━━┩
│ builtin::code_interpreter │ code-interpreter       │ None │ None         │
│ builtin::memory           │ memory-runtime         │ None │ None         │
│ builtin::websearch        │ tavily-search          │ None │ None         │
│ mcp-memory                │ model-context-protocol │ None │ None         │
│ brave-search              │ model-context-protocol │ None │ None         │
└───────────────────────────┴────────────────────────┴──────┴──────────────┘
```
> add toolgroup cli commands

- .github/workflows/publish-to-test-pypi.yml
- add a workflow dispatch trigger for accepting repository_dispatch from llama-stack
- After merging to master, test with llama-stack workflow trigger
```
curl -L \
-X POST \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer PAT_TOKEN" \
-H "X-GitHub-Api-Version: 2022-11-28" \
https://api.github.com/repos/meta-llama/llama-stack-client-python/dispatches \
-d '{"event_type":"build-client-package","client_payload":{"source":"llama-stack-nightly", "version": "rc234"}}'
```
> [CICD] testpypi workflow add repository_dispatch trigger from llama-stack

- src/llama_stack_client/lib/inference/event_logger.py
> fix event logger for ContentDelta update

- README.md
some links in the readme are to the stale repository url under an old org/account
this pr updates them to the new https://github.com/meta-llama/llama-stack-client-python base url
> update github links to official meta-llama org/account

- src/llama_stack_client/lib/cli/configure.py
- src/llama_stack_client/lib/cli/llama_stack_client.py
**Summary:**
This PR is adding the --api-key option for the llama-stack-client
**Test Plan:**
Config client:
```
llama-stack-client configure --endpoint=https://api.hostname.com --api-key='_API_KEY_'
Done! You can now use the Llama Stack Client CLI with endpoint https://api.hostname.com
```
Try listing the models
```
llama-stack-client models list
┏━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━┓
┃ identifier            ┃ provider_id ┃ provider_resource_id  ┃ metadata ┃ model_type ┃
┡━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━┩
│ llama3.1-8b-instruct  │ meta-llama  │ llama3.1-8b-instruct  │ {}       │ llm        │
│ llama3.3-70b-instruct │ meta-llama  │ llama3.3-70b-instruct │ {}       │ llm        │
│ …
```
> Adding API key support

- src/llama_stack_client/lib/cli/post_training/post_training.py
Summary:
`llama-stack-client` was broken.
```
llama-stack-client
Traceback (most recent call last):
File "/opt/homebrew/Caskroom/miniconda/base/envs/llama-stack/bin/llama-stack-client", line 5, in <module>
from llama_stack_client.lib.cli.llama_stack_client import main
File "/opt/homebrew/Caskroom/miniconda/base/envs/llama-stack/lib/python3.10/site-packages/llama_stack_client/lib/cli/llama_stack_client.py", line 23, in <module>
from .post_training import post_training
File "/opt/homebrew/Caskroom/miniconda/base/envs/llama-stack/lib/python3.10/site-packages/llama_stack_client/lib/cli/post_training/__init__.py", line 7, in <module>
from .post_training import post_training
File "/opt/homebrew/Caskroom/miniconda/base/envs/llama-stack/lib/python3.10/site-packages/llama_stack_client/lib/cli/post_ …
```
> Fix import error "cannot import name 'AlgorithmConfig'"

- src/llama_stack_client/resources/inference.py
This is result of sync stainless script changes so that we can send correct header based on the stream arg:
* We modified spec to separate application/json from text/event-stream responses (https://github.com/meta-llama/llama-stack/pull/910)
* We modified stainless sync script to include text/event-stream when stream arg is True (https://github.com/fairinternal/llama-oss-operations/pull/68)
> Sync updates from stainless branch: main

- src/llama_stack_client/lib/agents/agent.py
- src/llama_stack_client/lib/agents/output_parser.py
- src/llama_stack_client/lib/agents/react/__init__.py
- src/llama_stack_client/lib/agents/react/agent.py
- src/llama_stack_client/lib/agents/react/output_parser.py
- src/llama_stack_client/lib/agents/react/prompts.py
- See https://github.com/meta-llama/llama-stack/discussions/975
**Changes**
✅  Bugfix ToolResponseMessage role
✅  Add ReACT default prompt + default output parser
✅  Add ReACTAgent wrapper
🚧  Remove ClientTool and simplify it as a decorator (separate PR, including llama-stack-apps)
✅  Make agent able to return structured outputs
- Note that some remote provider do not support response_format structured outputs, add it as an optional flag when calling `ReActAgent` wrapper. 
see test in https://github.com/meta-llama/llama-stack-apps/pull/166
> [RFC] Client Agent SDK OutputParser

- src/llama_stack_client/lib/agents/agent.py
- src/llama_stack_client/lib/agents/client_tool.py
- src/llama_stack_client/lib/agents/react/agent.py
- Add decorator for on callables for defining client side custom tools
- Addresses: https://github.com/meta-llama/llama-stack/issues/948
Usage:
```python
@client_tool
def add(x: int, y: int) -> int:
'''Add 2 integer numbers
:param x: integer 1
:param y: integer 2
:returns: sum of x + y
'''
return x + y
```
`add` will be a ClientTool that can be passed
- Working example in: https://github.com/meta-llama/llama-stack-apps/pull/166
> [SDK] add tool decorator helper for custom client tools

- src/llama_stack_client/lib/inference/utils.py
Summary:
Adding `MessageAttachment.base64(path)` so that sending attachment will look like this:
```
from llama_stack_client.lib.inference.utils import MessageAttachment
response = client.inference.chat_completion(
model_id="meta-llama/llama3.2-11b-vision-instruct",
messages=[
{
"role": "user",
"content": {
"type": "image",
"image": {
"data": MessageAttachment.base64("images/tennis-game.png")
}
}
},
{
"role": "user",
"content": "What's in this image?",
}
]
)
```
Test Plan:
```
pip install .
from llama_stack_client import LlamaStackClient
from llama_stack_client.lib.inference.utils import MessageAttachment
client = LlamaStackClient(
base_url='localhost:8321'
)
response = client.inference.chat_completion(
model_id="meta-llama/llama3.2-11b-vision-instruct",
messages=[
{
"role": "user", …
```
> Adding util to help developers add message attachment

- src/llama_stack_client/lib/cli/models/models.py
identifier is not a valid argument for `retrieve` but model_id is.
```
╰─ llama-stack-client models get meta-llama/Llama-3.2-3B-Instruct
╭────────────────────────────────────────────────────────────────────────────────────╮
│ Failed to get model details                                                        │
│                                                                                    │
│ Error Type: TypeError                                                              │
│ Details: ModelsResource.retrieve() got an unexpected keyword argument 'identifier' │
╰────────────────────────────────────────────────────────────────────────────────────╯
```
the error now is: 
```
╰─ …
```
> fix: broken .retrieve call using `identifier=`

- src/llama_stack_client/lib/cli/configure.py
- src/llama_stack_client/lib/cli/datasets/datasets.py
- src/llama_stack_client/lib/cli/eval/eval.py
- src/llama_stack_client/lib/cli/eval_tasks/eval_tasks.py
- src/llama_stack_client/lib/cli/inference/inference.py
- src/llama_stack_client/lib/cli/inspect/inspect.py
- src/llama_stack_client/lib/cli/models/models.py
- src/llama_stack_client/lib/cli/post_training/post_training.py
- src/llama_stack_client/lib/cli/providers/providers.py
- src/llama_stack_client/lib/cli/scoring_functions/scoring_functions.py
- src/llama_stack_client/lib/cli/shields/shields.py
- src/llama_stack_client/lib/cli/toolgroups/toolgroups.py
- src/llama_stack_client/lib/cli/vector_dbs/vector_dbs.py
Descriptions were repetitive and verbose, some were truncated by click
rendering (trailing ... ellipsis). This is an attempt to simplify /
shorten / clarify the descriptions.
Before:
```
 llama-stack-client --help
Usage: llama-stack-client [OPTIONS] COMMAND [ARGS]...
Welcome to the LlamaStackClient CLI
Options:
--version        Show the version and exit.
--endpoint TEXT  Llama Stack distribution endpoint
--api-key TEXT   Llama Stack distribution API key
--config TEXT    Path to config file
--help           Show this message and exit.
Commands:
configure          Configure Llama Stack Client CLI
datasets           Query details about available datasets on Llama...
eval               Run …
```
> Humanize CLI command group descriptions a bit

- src/llama_stack_client/lib/cli/providers/list.py
currently this command always errors out due to using .items() on a list.
```
╭─────────────────────────────────────────────────╮
│ Failed to list providers                        │
│                                                 │
│ Error Type: AttributeError                      │
│ Details: 'list' object has no attribute 'items' │
```
Fix the loop that looks at the list response
after fixing: output on Ollama distribution is the following:
```
┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ API          ┃ Provider ID           ┃ Provider Type                 ┃
┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ inference    │ ollama                │ remote::ollama                │
│ inference    │ sentence-transformers │ …
```
> fix: llama-stack-client providers list

- src/llama_stack_client/lib/agents/react/agent.py
- update react agent to use tool_config + system prompt override
```
python -m examples.agents.react_agent
```
> refactor: update react_agent to use tool_config

- README.md
Update the example to reflect current API
Copy paste the example in the README and check the output. Without this change an error is raised:
```python
python3 hello.py 
Traceback (most recent call last):
File "/Users/bmuthuka/wa/meta-llama/baiju-experiments/hello.py", line 8, in <module>
response = client.inference.chat_completion(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/miniconda3/envs/myml/lib/python3.12/site-packages/llama_stack_client/_utils/_utils.py", line 274, in wrapper
raise TypeError(msg)
TypeError: Missing required arguments; Expected either ('messages' and 'model_id') or ('messages', 'model_id' and 'stream') arguments to be given
```
> Update the example to reflect current API

- src/llama_stack_client/lib/cli/inference/inference.py
today, to chat with a model, a user has to run one command per completion. add --session which enables a user to have an interactive chat session with the inference model. --session can be passed with or without --message. If no --message is passed, the user is prompted to give the first message.
This is useful as it also enables context to be saved between each completion unlike today.
```
llama-stack-client inference chat-completion --session
>>> hi whats up!
Assistant> Not much! How's your day going so far? Is there something I can help you with or would you like to chat?
>>> what color is the sky?
Assistant> The color of the sky can vary depending on the time of day and atmospheric conditions. Here are some common colors you might see:
* During the daytime, when the sun is overhead, …
```
> feat: add support for chat sessions

- src/llama_stack_client/lib/agents/agent.py
- src/llama_stack_client/lib/agents/client_tool.py
- src/llama_stack_client/lib/agents/event_logger.py
- src/llama_stack_client/lib/agents/react/agent.py
- src/llama_stack_client/lib/agents/react/tool_parser.py
- Cannot take `Any` in structured outputs for ReActOutput ( updated the structure ) 
- open-ai takes "string" instead of "str" in tool param 
- better error handling in event logger
> fix: React Agent for non-llama models 

- src/llama_stack_client/lib/agents/agent.py
This PR simplifies the Agent SDK (related to https://github.com/meta-llama/llama-stack-client-python/issues/160)
Before
```
agent_config = AgentConfig(models, instructions, toolgroups, client_tools, ...)
agent = Agent(client, agent_config, client_tools)
```
Now just:
```
agent = Agent(client, model, instructions, tools, ...)
```
See https://github.com/meta-llama/llama-stack-apps/pull/200/files for example.
Will update all examples and docs once this PR looks good.
Run test_agents.py with
https://github.com/meta-llama/llama-stack/pull/1402
> feat: new Agent API

- src/llama_stack_client/lib/agents/agent.py
- src/llama_stack_client/lib/agents/react/tool_parser.py
- Custom tool_parser on client side is not working correctly with latest change unifying max_infer_iters. 
- This is b/c we output an `end_of_message`
- Temporary is to still keep track of n_iters when we have custom tool_parser on client, this will not be needed when we move ReAct to server side. 
```
python -m examples.agents.react_agent localhost 8321
```
> fix: react agent with custom tool parser n_iters

- src/llama_stack_client/lib/agents/agent.py
Summary:
otherwise errors on L127
Test Plan:
py.test -v -s --nbval-lax ./docs/getting_started.ipynb with https://github.com/meta-llama/llama-stack/pull/1402
> fix(agent): initialize toolgroups/client_tools

- src/llama_stack_client/lib/agents/agent.py
- src/llama_stack_client/lib/agents/client_tool.py
- Introduce `AsyncAgent` -- an async version of Agent wrapper using AsyncLlamaStackClient
- Enable async def with client_tool decorator
- Closes https://github.com/meta-llama/llama-stack/issues/1391
```python
class Agent:
def create_session(...): ...
def create_turn(...): ...
class AsyncAgent
async def create_session(...): ...
async def create_turn(...): ...
```
> NOTE, there's some code duplication to keep the distinction and avoid too many if/else 
- test with script in: https://github.com/meta-llama/llama-stack-apps/blob/async_agent/examples/agents/async_agent.py
- test with ReAct agent
```
pytest -v tests/client-sdk/agents/test_agents.py --inference-model …
```
> feat: async agent wrapper

- src/llama_stack_client/lib/cli/configure.py
- src/llama_stack_client/lib/cli/datasets/datasets.py
- src/llama_stack_client/lib/cli/datasets/list.py
- src/llama_stack_client/lib/cli/datasets/register.py
- src/llama_stack_client/lib/cli/eval/eval.py
- src/llama_stack_client/lib/cli/eval/run_benchmark.py
- src/llama_stack_client/lib/cli/eval/run_scoring.py
- src/llama_stack_client/lib/cli/eval_tasks/eval_tasks.py
- src/llama_stack_client/lib/cli/eval_tasks/list.py
- src/llama_stack_client/lib/cli/inference/inference.py
- src/llama_stack_client/lib/cli/inspect/inspect.py
- src/llama_stack_client/lib/cli/inspect/version.py
- src/llama_stack_client/lib/cli/llama_stack_client.py
- src/llama_stack_client/lib/cli/models/models.py
- src/llama_stack_client/lib/cli/post_training/post_training.py
- src/llama_stack_client/lib/cli/providers/list.py
- src/llama_stack_client/lib/cli/providers/providers.py
- src/llama_stack_client/lib/cli/scoring_functions/list.py
- src/llama_stack_client/lib/cli/scoring_functions/scoring_functions.py
- src/llama_stack_client/lib/cli/shields/shields.py
- src/llama_stack_client/lib/cli/toolgroups/toolgroups.py
- src/llama_stack_client/lib/cli/vector_dbs/vector_dbs.py
Updated each command in the CLI to support the `-h` flag for displaying usage instructions.
This PR adds support for the -h help flag to all CLI commands. It enables users to view usage instructions and command options by appending -h or --help to any command in the CLI. This enhancement improves the usability of the CLI by providing a consistent and easy way for users to access command-specific help information. The help flag functionality is implemented across all commands, ensuring that every CLI command supports this feature.
Manual Testing:
Run each CLI command with the -h or --help flag.
Verify that the correct help message is displayed for each command, including the command options, arguments, and usage instructions.
> Add `-h` help flag support to all CLI commands

- src/llama_stack_client/lib/agents/client_tool.py
Summary:
Moving this to litellm inference instead https://github.com/meta-llama/llama-stack/pull/1565
Test Plan:
LLAMA_STACK_CONFIG=fireworks pytest -s -v tests/integration/agents/test_agents.py --safety-shield meta-llama/Llama-Guard-3-8B --text-model meta-llama/Llama-3.1-8B-Instruct
> chore: remove litellm type conversion

- src/llama_stack_client/lib/cli/configure.py
currently `llama-stack-client configure` allows a user to set up with a invalid URL such as ` ['::', '0.0.0.0']:8321` and then any subsequent command fails due to improperly reading the bad URL from the config.yaml
after:
> fix: validate endpoint url

- src/llama_stack_client/lib/cli/providers/inspect.py
- src/llama_stack_client/lib/cli/providers/providers.py
- src/llama_stack_client/resources/providers.py
- src/llama_stack_client/types/provider_get_response.py
- src/llama_stack_client/types/provider_info.py
allow a user to see certain parts of the provider configuration for a specified provider. This is the cli code corresponding to https://github.com/meta-llama/llama-stack/pull/1429
This PR introduces:
-  `llama-stack-client providers inspect`
- amends `llama-stack-client providers list` to use `/v1/providers`
- `GetProviderResponse` to handle the response from these new API calls
> feat: `llama-stack-client providers inspect PROVIDER_ID`

- src/llama_stack_client/lib/cli/providers/inspect.py
after regenerating the client with stainless and updating the openAPI spec, `inspect` is now `retreive`. fix `llama-stack-client provider inspect`
> fix: `llama-stack-client provider inspect` should use retrieve

- src/llama_stack_client/lib/agents/agent.py
Before:
`NoneType has no 'payload'...`
> fix(agent): better error handling

- src/llama_stack_client/lib/agents/react/tool_parser.py
Running into this error: 
```
python test_vision.py
Traceback (most recent call last):
File "/Users/kaiwu/work/internal-llama-stack-apps/examples/computer_use/test_vision.py", line 5, in <module>
from llama_stack_client.lib.agents.react.agent import ReActAgent
File "/opt/homebrew/anaconda3/envs/dmg/lib/python3.10/site-packages/llama_stack_client/lib/agents/react/agent.py", line 20, in <module>
from .tool_parser import ReActOutput, ReActToolParser
File "/opt/homebrew/anaconda3/envs/dmg/lib/python3.10/site-packages/llama_stack_client/lib/agents/react/tool_parser.py", line 35, in <module>
class ReActToolParser(ToolParser):
File "/opt/homebrew/anaconda3/envs/dmg/lib/python3.10/site-packages/llama_stack_client/lib/agents/react/tool_parser.py", line 36, in ReActToolParser
@override
NameError: …
```
> remove override in react agent 

- src/llama_stack_client/_client.py
- src/llama_stack_client/resources/__init__.py
- src/llama_stack_client/resources/responses.py
- src/llama_stack_client/types/__init__.py
- src/llama_stack_client/types/response_create_params.py
- src/llama_stack_client/types/response_object.py
- src/llama_stack_client/types/response_object_stream.py
- tests/api_resources/test_responses.py
client-side support for the in-progress API surface: https://github.com/meta-llama/llama-stack/pull/1989
> feat: client.responses.create() and client.responses.retrieve()
